'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourcesLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("inoXCA.ResourcesLang", GetType(ResourcesLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To generate the private key the following crypto engine is used: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AboutCrypto() As String
            Get
                Return ResourceManager.GetString("AboutCrypto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AboutInfo() As String
            Get
                Return ResourceManager.GetString("AboutInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AboutVersion() As String
            Get
                Return ResourceManager.GetString("AboutVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copyright 2021 - {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationCopyright() As String
            Get
                Return ResourceManager.GetString("ApplicationCopyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This software is developed under AGPL v3. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationDescription() As String
            Get
                Return ResourceManager.GetString("ApplicationDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdCancel() As String
            Get
                Return ResourceManager.GetString("CmdCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdClose() As String
            Get
                Return ResourceManager.GetString("CmdClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdExport() As String
            Get
                Return ResourceManager.GetString("CmdExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export checked ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdExportBulk() As String
            Get
                Return ResourceManager.GetString("CmdExportBulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Define CRL-file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdFileSelect() As String
            Get
                Return ResourceManager.GetString("CmdFileSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdLicense() As String
            Get
                Return ResourceManager.GetString("CmdLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdOK() As String
            Get
                Return ResourceManager.GetString("CmdOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdSave() As String
            Get
                Return ResourceManager.GetString("CmdSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save and close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CmdSaveClose() As String
            Get
                Return ResourceManager.GetString("CmdSaveClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCRLExport() As String
            Get
                Return ResourceManager.GetString("ExportCRLExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name of CA ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCRLName() As String
            Get
                Return ResourceManager.GetString("ExportCRLName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Number of revoked certs ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCRLNoRevoked() As String
            Get
                Return ResourceManager.GetString("ExportCRLNoRevoked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name of export file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCRLPath() As String
            Get
                Return ResourceManager.GetString("ExportCRLPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export CRL files ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCRLTitle() As String
            Get
                Return ResourceManager.GetString("ExportCRLTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Next Update ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCRLUpdate() As String
            Get
                Return ResourceManager.GetString("ExportCRLUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die XCA Pwassword: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCADBPW() As String
            Get
                Return ResourceManager.GetString("ExportXCADBPW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCAFileType() As String
            Get
                Return ResourceManager.GetString("ExportXCAFileType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die P12 file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCAP12() As String
            Get
                Return ResourceManager.GetString("ExportXCAP12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die P12 file with root chain ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCAP12Chain() As String
            Get
                Return ResourceManager.GetString("ExportXCAP12Chain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cerificate file: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCAPEMFile() As String
            Get
                Return ResourceManager.GetString("ExportXCAPEMFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Certificate password: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCAPEMPW() As String
            Get
                Return ResourceManager.GetString("ExportXCAPEMPW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Private PEM key ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCAPriv() As String
            Get
                Return ResourceManager.GetString("ExportXCAPriv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export from XCA to certificate file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportXCATitle() As String
            Get
                Return ResourceManager.GetString("ExportXCATitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CRL-file (*.crl) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FileCRL() As String
            Get
                Return ResourceManager.GetString("FileCRL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die P12-file (*.p12) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FileP12() As String
            Get
                Return ResourceManager.GetString("FileP12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PEM-file (*.pem) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FilePEM() As String
            Get
                Return ResourceManager.GetString("FilePEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die XCA-database (*.xdb) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FileXCA() As String
            Get
                Return ResourceManager.GetString("FileXCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainAbout() As String
            Get
                Return ResourceManager.GetString("MainAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainFile() As String
            Get
                Return ResourceManager.GetString("MainFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainHelp() As String
            Get
                Return ResourceManager.GetString("MainHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New window ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainNewWindow() As String
            Get
                Return ResourceManager.GetString("MainNewWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainOptions() As String
            Get
                Return ResourceManager.GetString("MainOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainQuit() As String
            Get
                Return ResourceManager.GetString("MainQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatus() As String
            Get
                Return ResourceManager.GetString("MainStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Statusbar ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatusbar() As String
            Get
                Return ResourceManager.GetString("MainStatusbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die inoXCA ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTitle() As String
            Get
                Return ResourceManager.GetString("MainTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainTools() As String
            Get
                Return ResourceManager.GetString("MainTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainView() As String
            Get
                Return ResourceManager.GetString("MainView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindow() As String
            Get
                Return ResourceManager.GetString("MainWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arrange Symbols ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindowsArrangeIcons() As String
            Get
                Return ResourceManager.GetString("MainWindowsArrangeIcons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cascade ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindowsCascade() As String
            Get
                Return ResourceManager.GetString("MainWindowsCascade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close all windows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindowsCloseAll() As String
            Get
                Return ResourceManager.GetString("MainWindowsCloseAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Horizontal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindowsHorizontal() As String
            Get
                Return ResourceManager.GetString("MainWindowsHorizontal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Vertical ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainWindowsVertical() As String
            Get
                Return ResourceManager.GetString("MainWindowsVertical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die XCA ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainXCA() As String
            Get
                Return ResourceManager.GetString("MainXCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Create PEM Bundle ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainXCABundle() As String
            Get
                Return ResourceManager.GetString("MainXCABundle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error loading certificate. The XCA password might be incorret. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgCertLoadError() As String
            Get
                Return ResourceManager.GetString("MsgCertLoadError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgHint() As String
            Get
                Return ResourceManager.GetString("MsgHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You need to set a folder to store certificates. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgMissingCertFolder() As String
            Get
                Return ResourceManager.GetString("MsgMissingCertFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Missing CRL-file for &apos;{0}&apos;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgMissingPath() As String
            Get
                Return ResourceManager.GetString("MsgMissingPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No certificate file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoPEM() As String
            Get
                Return ResourceManager.GetString("MsgNoPEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No password for certificate file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoPEMPW() As String
            Get
                Return ResourceManager.GetString("MsgNoPEMPW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No private key available. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoPrivKey() As String
            Get
                Return ResourceManager.GetString("MsgNoPrivKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No certificate selected. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoSelection() As String
            Get
                Return ResourceManager.GetString("MsgNoSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No XCA file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoXCA() As String
            Get
                Return ResourceManager.GetString("MsgNoXCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No password for XCA file given. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MsgNoXCAPW() As String
            Get
                Return ResourceManager.GetString("MsgNoXCAPW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 1. Select xca file to see content. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PemInfo1() As String
            Get
                Return ResourceManager.GetString("PemInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 2. Select pem file to export certificates to bundle. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PemInfo2() As String
            Get
                Return ResourceManager.GetString("PemInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PEM file: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PemPem() As String
            Get
                Return ResourceManager.GetString("PemPem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die PEM bundle from XCA ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PemTitle() As String
            Get
                Return ResourceManager.GetString("PemTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die XCA file: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PemXCA() As String
            Get
                Return ResourceManager.GetString("PemXCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsLanguage() As String
            Get
                Return ResourceManager.GetString("SettingsLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The application needs as restart to apply the language settings. Do you want to restart? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsRestart() As String
            Get
                Return ResourceManager.GetString("SettingsRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SettingsTitle() As String
            Get
                Return ResourceManager.GetString("SettingsTitle", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
